### ISSUE TITLE
Version Sorting and max published version

### ISSUE THREAD

**Issue by kumarjoshi** [Snowflake-Labs/snowchange#13]
When applying change scripts, this is the order snowchange follows:
```
Max applied change script version: None
Applying change script V0.0.1__create_db.sql
Applying change script V0.0.2__create_schema_1.sql
Applying change script V0.1.0__create_schema_2.sql
Applying change script V0.1.1__create_table.sql
Applying change script V0.1__create_schema_3.sql
Successfully applied 5 change scripts (skipping 0)
Completed successfully
```

V0.1 should be the max published version as it's applied after V0.1.0 and V0.1.1 
But sorted_alphanumeric returns 0.1.1 as the max_published_version
change_history_sorted: ['0.0.1', '0.0.2', '0.1', '0.1.0', '0.1.1']

**Comment by jeremiahhansen** [comment]
Hey there @kumarjoshi, thanks for raising this. Are you saying that the all_script_names_sorted and change_history_sorted lists are sorted differently? That's strange since they both use the same sorted_alphanumeric() function. I'll take a look.

But I would advise against using two different naming conventions for the version, that can lead to weird problems. You should adopt a standard like two parts or three parts and stick with it. I will also update the documentation to make that clear.

**Comment by kumarjoshi** [comment]
Thank you @jeremiahhansen. 
Yes. According to the change script log above, V0.1__create_schema_3.sql was applied last. It matches INSTALLED_ON values in the database:
```
0.0.1	2020-10-06 18:15:04
0.0.2	2020-10-06 18:15:09
0.1.0	2020-10-06 18:15:15
0.1.1	2020-10-06 18:15:23
0.1	2020-10-06 18:15:30
```
So when I apply the next change script, I should be getting max_published_version = 0.1
I logged the following values:
change_history_sorted = ['0.0.1', '0.0.2', '0.1', '0.1.0', '0.1.1']
max_published_version = change_history_sorted[-1]
max_published_version = 0.1.1 which doesn't match the database value. 

You are absolutely correct about sticking to standards, but since the code doesn't restrict that, I was trying to test non-standard file names. 

Also, to get the max_published_version from the database, instead of getting all the values, adding them to a list and then sorting them, is it possible to use INSTALLED_ON timestamp to get the max_published_version without relying on version name, provided INSTALLED_ON has milliseconds precision to avoid clash ? Something like this:

`SELECT "VERSION"  FROM SNOWCHANGE.CHANGE_HISTORY  WHERE INSTALLED_ON  =  (SELECT MAX (INSTALLED_ON) FROM SNOWCHANGE.CHANGE_HISTORY) ;`

**Comment by sfc-gh-jhansen** [comment]
Hey @kumarjoshi, just want to follow-up here. As you know from the recent PR, we've recently released changes to support repeatable migrations and updated the logic to get the max version from the database to use a max on INSTALLED_ON. Are you still seeing issues with the Python sorting logic like you described above?

**Comment by kumarjoshi** [comment]
Thank you @sfc-gh-jhansen !  No issues with this logic anymore.
