### ISSUE TITLE
Snowchange not picking up files with uppercase extension

### ISSUE THREAD

**Issue by kavengagne** [Snowflake-Labs/snowchange#17]
Hey guys,

Thank you for the very useful script that is Snowchange.

We are having an issue when people using Windows are sending files into the pipeline with names like

```V1.2__something.SQL```

These files are being ignored by Snowchange because the regexp used for files is

```python
script_name_parts = re.search(r'^([V])(.+)__(.+)\.sql$', file_name.strip())
repeatable_script_name_parts = re.search(r'^([R])__(.+)\.sql$', file_name.strip())
```

I think these 2 regular expressions should ignore case, at least for the extension part of the filename.

What do you think? I can send a PR if required.

**Comment by sfc-gh-jhansen** [comment]
Just pushed a fix for this! And just updated the package in PyPI so you can now install snowchange via pip!
