### ISSUE TITLE
ENV field in CHANGE_HISTORY table

### ISSUE THREAD

**Issue by qqcvd** [Snowflake-Labs/snowchange#18]
Hello,

When I use snowpipe in my installation script, I use a variable --vars "{"ENV":"DEV"}"  to install into a specific environment (using the "USE DATABASE DB_{{ ENV }}_WH" command). 
My DBs are named like DB_DEV_WH, DB_UAT_WH, DB_PPD_WH, DB_PRD_WH.
Would it be possible to have a 'environment' field added in the CHANGE_HISTORY table ?

**Comment by sfc-gh-jhansen** [comment]
Thanks for the suggestion @qqcvd. I thought about this, adding an environment column to CHANGE_HISTORY table, but after playing around with it a bit decided that it would be more flexible to add the `-c` option and let the user decided exactly how to deal with environments. Part of the challenge is that if we add native environment support then there needs to be a way to incorporate that into the change scripts themselves. To be fair when I thought through this before we didn't have variable support which made it more difficult. But that said I still think it's more flexible this way.

What's your primary concern? Is it to have only a single CHANGE_HISTORY table per Snowflake account for all environments? The way it works currently you'd have to maintain a separate CHANGE_HISTORY table per environment and leverage the `-c` option to give each a different name (they can all be in the same DB or separate ones).

**Comment by qqcvd** [comment]
to be short, before I encounter you tool, I had already done a logging system to log the installations of my SQL packages. So there is a PACKAGE_DELIVERY_TRACKING table in each DB (an environment = only one DB)  with the following fields :
	PACKAGE_ID 
	INSTALL_DATE
	ENVIRONMENT (DEV / INT / PPD / PRD)
	TYPE_ACTION (INSTALL / ROLLBACK)
	USERNAME 
	DESCRIPTION
On top of this, in the SF account, there is an admin DB which contains a View accross all the tables, in order to present the log like this (thanks to an union and a sql pivot) : 
```
PACK_ID      INT                    PPD                    PRD
S26_US1000   2020-06-29 16:47:09    [NULL]                 [NULL]
S26_US123    2020-07-06 14:23:42    2020-07-09 16:27:08    [NULL]
S26_US575    2020-10-09 15:49:15    2020-10-12 11:53:54    2020-10-14 11:54:33
```
My aim is to have a map of the packages installed with the dates.

I agree that I can do the same thing on top of CHANGE_HISTORY table, with the -c option and the variable support.
