### ISSUE TITLE
delivery version option

### ISSUE THREAD

**Issue by qqcvd** [Snowflake-Labs/snowchange#20]
Hello, 
I'd like to share with you another point : I do not have the same version of my delivery accross the different environment.s
For example : 
1.10 in integration
1.9 in UAT
1.8 in preprod 
1.7 in prod
Thus , we would need to precise to Snowchange the version to install.
If I execute Snowchange against the Production environment, I only want the 1.8 version to be deployed (but not til the 1.10 version)

**Comment by sfc-gh-jhansen** [comment]
There are certainly many different SDLC approaches, but in my experience the situation you described is usually managed with your branching strategy in source control (and not in the DCM tool).
