### ISSUE TITLE
Define DB in snowflake connection rather than environment variable

### ISSUE THREAD

**Issue by monikaac** [Snowflake-Labs/snowchange#24]
Hello,

We have one snowflake account and within that account we have all of our lower environments defined as databases that we clone from prod. We also use code generation scripts to generate some of our standard tables and workflows. We are currently defining the environment by setting a variable and manually adding the "use database {{ db_var }};" in front of all of our generated code (and non generated code). We would like to instead have an option to add the DB to the connection string into snowflake within the python Snowchange job. Our branches are named the same as our DBs so then we can dynamically set the DB in the YAML file and not have to include the "use database {{ db_var }};" at the top of all of our SQL scripts. We are finding that difficult to remember to do. 

I can make the change and request it to be merged. Would that be acceptable?

**Comment by sfc-gh-jhansen** [comment]
Hey there @monikaac, thanks for the suggestion, and I think that makes sense. It sounds like your suggesting adding a command line argument to specify the database name and updating the apply_change_script() function to pass the database name to the main execute_snowflake_query() call. I think that would be a nice addition for snowchange users and still allow snowchange to be very flexible. Please do make the change and submit a PR!

**Comment by sfc-gh-jhansen** [comment]
@monikaac, yesterday I released version 2.6 and was able to include this change in that release. So nothing to do from your end. Hope it helps!
