### ISSUE TITLE
Database for change_history exists

### ISSUE THREAD

**Issue by nugic** [Snowflake-Labs/snowchange#25]
This is not an issue or a bug, but rather a suggestion to think about.
I don't want to give my deployer user any grants outside of the database that it is supposed to work with, meaning also no rights to create a database. But snowchange script executes a "CREATE DATABASE IF NOT EXISTS" for creating the CHANGE_HISTORY table, which then is followed by error. In my view, we don't want a new db for change_history in any case, so I would rather get an error, when the defined db doesn't exist. 
But I understand that other users might find it an useful feature, so my suggestion would be to change the script so, that db creation right is not needed by default.
So far I can easily leave out the part of the code where this is tried in my local env.

**Comment by sfc-gh-jhansen** [comment]
Hey @nugic, please check out issue #15 which is the same. I'll close this as a duplicate.
