### ISSUE TITLE
Feature: Dry run option

### ISSUE THREAD

**Issue by michael-robbins** [Snowflake-Labs/snowchange#27]
Just throwing this out there, if it's possible to land a 'dry run' cmd line arg that will print out what snowchange "is about to do" without applying it?

Concept: https://flywaydb.org/documentation/concepts/dryruns

**Comment by henrymcconville** [comment]
Had a go at implementing this in #28

**Comment by sfc-gh-jhansen** [comment]
Thanks @henrymcconville! The changes look pretty good, just one some clean-up item it seems.

**Comment by sfc-gh-jhansen** [comment]
Alright @michael-robbins, I just merged the changes and published an updated PyPI package. Thanks for the new feature @henrymcconville!

**Comment by ramandatascientist** [comment]
Hi @sfc-gh-jhansen @henrymcconville  I have identified one issue with dry-run flag in schema-change. Also captured in an issue as well

https://github.com/Snowflake-Labs/schemachange/issues/177

`dry-run=true` flag  only list the `.SQL` files that it will run but does not compile the file to show any SQL compilation or permissions errors in dry run mode (eg: invalid column, permission missing etc)

is this expected or a bug?
