### ISSUE TITLE
Minor typo: Flayway -> Flyway

### ISSUE THREAD

**Issue by sfc-gh-space** [Snowflake-Labs/snowchange#34]
Minor typo in title: Flayway -> Flyway:

https://github.com/Snowflake-Labs/snowchange/commit/00c8b8450e3660280d5ee2a7dce49b418d688883

**Comment by sfc-gh-jhansen** [comment]
Thanks for the pointing that out @sfc-gh-space, but it looks like it's just in the commit description. I checked the repository and don't see it anywhere in the code, so we should be OK.
