### ISSUE TITLE
Derive database context from the folder structure

### ISSUE THREAD

**Issue by francesco-quaratino** [Snowflake-Labs/snowchange#9]
I would like the context to be (optionally) derived by the folder structure (that is the \databases\<database_name>) instead of being necessarily supplied by using an explicit USE <DATABASE> command or by naming all objects with a three-part name (<database name>.<schema name>.<object name>). This to make the scripts portable to the different database environments, in other words, to allow the same scripts to be deployed across <databasename>_DEV, <databasename>_UAT and so on.

**Comment by jeremiahhansen** [comment]
Hey there, thanks for the feedback. This was actually the way that snowchange used to function but it led to significant limitations. The biggest limitation was that it didn't properly allow for dynamic database names, for example in scripts with 3-part database names. And it also caused issues with cross database dependencies. What snowchange needs is a variable/macro feature so that scripts can dynamically update the database names. I've briefly looked into Jinja as well as using dbt for this. If you have any other ideas about how to implement this I'd love to hear them!

**Comment by francesco-quaratino** [comment]
Hi Jeremiah, what about a new (optional) argument?

    parser.add_argument('-td', '--target-database', type=str,
                        help='The deployment target database name (e.g. MY_DB_DEV)', required=false)
 
I am now actually trying it out as a required argument, that, also, replaces the default _metadata_database_name  when --change-history-table argument is not provided. Although I understand this solution is a bit patchy, it does fit well with the way my team is trying to work with Snowflake, that is building the change_history table in the target database by default with each environment (dev, uat, prod) made out of a separate database in the same Snowflake account and, therefore, all the scripts applicable from dev to prod without any change. The only difference is in the "python snowchange.py  --target-database MYDB_DEV ..." run, which at this minute I haven't managed to make within a DevOps pipeline yet, therefore is made out of a ms-dos batch file per environment, shared among the team members.

**Comment by jeremiahhansen** [comment]
Sorry for the delay here. I may not understand the exact situation here, but sounds like what the -c/--change-history-table parameter provides already. I just finished changes to a new feature which will allow for variables in snowchange scripts. This should enable folks to support multiple environments (dev, test, prod) in a single Snowflake account, while still support cross database joins! The new version 2.2.0 should be available soon. Please let me know if that still doesn't meet your needs.

**Comment by jeremiahhansen** [comment]
Alright @francesco-quaratino, I just released new variable support which will enable people to support multiple environments (dev, test, prod, etc.) in a single Snowflake account. I believe that between this feature and what the -c/--change-history-table parameter already provides you should have everything you need. Please see the CHANGELOG.md and README.md files for more details and let me know if I can close this issue.
